### ISSUE TITLE
커스템 UI 구현

### ISSUE THREAD

**Issue by hyeone999** [cake-it/frontend#14]
## Description
커스템 UI 구현

## Todo
- [x] 카테고리 tab bar custom
- [ ] 최초 렌더링시 가이드 wrapper
- [x] 이미지 선택 기능 (테두리 변경, 스크롤뷰)
